fix for https://github.com/OasisLMF/OasisUI/issues/309
OasisLMF/OasisUI pull request #310
Opened 2023-11-09 14:52 UTC by dholdaway

a fix for https://github.com/OasisLMF/OasisUI/issues/309

2023-11-09 15:23 UTC, sambles requested changes

2023-11-09 15:23 UTC, sambles commented on docker/Dockerfile.oasisui_development
> +COPY ../BFE_RShiny/oasisui/DESCRIPTION ./BFE_RShiny/oasisui/DESCRIPTION
This needs reverting back

2023-11-10 13:41 UTC, dholdaway commented on docker/Dockerfile.oasisui_development
> +COPY ../BFE_RShiny/oasisui/DESCRIPTION ./BFE_RShiny/oasisui/DESCRIPTION
addressed, please review and approve.

2023-11-10 14:40 UTC, sambles approved these changes

2023-11-10 14:40 UTC, merged